#jekyll configuration
url: "https://rodrigobivarazevedo.github.io/research-paper/"
title: AI in the healthcare sector
author: Rodrigo Azevedo
name: rodrigobivarazevedo
email: rodrigobivarazevedo@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  How can Artificial Intelligence create efficiency in Digital Health
show_excerpts: false

 social_links:
    - { platform: github,         user_url: "https://github.com/rodrigobivarazevedo" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/rodrigo-azevedo-b25940258/" }
    

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown
theme: minima


