#jekyll configuration
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Artificial Intelligence in Medicine]
description: [How can AI create efficiency and effectiveness in Digital Health. What are the benefits and challenges to come.]
