# jekyll configuration
title: Artificial Intelligence in Medicine
author:
  name: rodrigobivarazevedo
  email: rodrigobivarazevedo@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  How can AI create effiency in Digital Health




  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/rodrigobivarazevedo"  }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/rodrigo-azevedo-b25940258/" }
   

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

